spring:
  datasource:
    url: jdbc:postgresql://${DB_ADDRESS}:${DB_PORT}/${DB_NAME}
#    url: jdbc:postgresql://localhost:5433/hospital
    username: ${DB_USER}
#    username: postgres
    password: ${DB_PASSWORD}
#    password: postgres
    driver-class-name: org.postgresql.Driver
    flyway:
      enabled: true
      baseline-on-migrate: true
jpa:
  hibernate:
    ddl-auto: validate
  properties:
     hibernate:
       format_sql: true
       dialect: org.hibernate.dialect.PostgreSQLDialect
       use_jdbc_metadata_defaults: true
  

